# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnderstandingAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=255)),
                ("inferred_role", models.CharField(max_length=50)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "confidence_band",
                    models.CharField(
                        choices=[
                            ("high", "High (>=0.90)"),
                            ("medium", "Medium (0.70 - 0.89)"),
                            ("low", "Low (<0.70)"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("evidence", models.TextField()),
                ("sample_patterns", models.JSONField(blank=True, default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("overridden", "User Overridden"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("user_override_role", models.CharField(blank=True, max_length=50)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="understanding_assessments",
                        to="datasets.datasetversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score"],
                "unique_together": {("version", "column_name")},
            },
        ),
    ]
