# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("append", "Append / Union Tables"),
                            ("join", "Join / Merge Tables"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "join_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left Outer Join"),
                            ("inner", "Inner Join"),
                            ("right", "Right Outer Join"),
                            ("outer", "Full Outer Join"),
                        ],
                        default="left",
                        max_length=20,
                    ),
                ),
                ("join_keys", models.JSONField(blank=True, default=dict)),
                ("column_mappings", models.JSONField(blank=True, default=dict)),
                ("cardinality_preview", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("records_produced", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_consolidations",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "resulting_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_consolidation",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "secondary_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_consolidations",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("matching_keys", models.JSONField(default=dict)),
                ("matched_records_count", models.PositiveIntegerField(default=0)),
                ("unmatched_primary_count", models.PositiveIntegerField(default=0)),
                ("unmatched_secondary_count", models.PositiveIntegerField(default=0)),
                ("control_total_field_1", models.CharField(blank=True, max_length=255)),
                ("control_total_field_2", models.CharField(blank=True, max_length=255)),
                (
                    "control_total_sum_1",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "control_total_sum_2",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "tolerance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("is_reconciled", models.BooleanField(default=False)),
                ("report_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_reconciliations",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "secondary_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_reconciliations",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
