# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("cleaning", "0002_initial"),
        ("datasets", "0001_initial"),
        ("reports", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="output_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datasets.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="report_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.reportrun",
            ),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datasets.sourcefile",
            ),
        ),
        migrations.AddField(
            model_name="workflowschedule",
            name="cleaning_recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="cleaning.cleaningrecipe",
            ),
        ),
        migrations.AddField(
            model_name="workflowschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowschedule",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="datasets.dataset",
            ),
        ),
        migrations.AddField(
            model_name="workflowschedule",
            name="report_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.reportdefinition",
            ),
        ),
        migrations.AddField(
            model_name="workflowschedule",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_runs",
                to="automation.workflowschedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowschedule",
            unique_together={("workspace", "name")},
        ),
    ]
