# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_models",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_models",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="SemanticMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("display_label", models.CharField(blank=True, max_length=255)),
                ("column_name", models.CharField(blank=True, max_length=255)),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("avg", "Average"),
                            ("count", "Count (Rows)"),
                            ("distinct_count", "Distinct Count"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                            ("formula", "Calculated Formula"),
                        ],
                        default="sum",
                        max_length=20,
                    ),
                ),
                ("formula_expression", models.CharField(blank=True, max_length=512)),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("currency", "Currency (e.g. ₹ / $)"),
                            ("percentage", "Percentage (%)"),
                            ("number", "Standard Number"),
                            ("integer", "Integer"),
                        ],
                        default="number",
                        max_length=20,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(blank=True, default="₹", max_length=10),
                ),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("is_kpi", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "semantic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="semantic_model.semanticmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("semantic_model", "name")},
            },
        ),
        migrations.CreateModel(
            name="SemanticDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("column_name", models.CharField(max_length=255)),
                ("display_label", models.CharField(blank=True, max_length=255)),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("categorical", "Categorical"),
                            ("time", "Date / Time"),
                            ("geographical", "Geographical"),
                            ("identifier", "Identifier"),
                        ],
                        default="categorical",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "semantic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="semantic_model.semanticmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("semantic_model", "name")},
            },
        ),
    ]
