# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("trim_whitespace", "Trim Whitespace"),
                            ("change_case", "Standardize Text Case"),
                            ("normalize_date", "Normalize Dates"),
                            ("convert_type", "Convert Column Type"),
                            ("remove_duplicates", "Remove Duplicate Rows"),
                            ("fill_missing", "Fill Missing Values"),
                            ("drop_missing", "Drop Rows with Missing Values"),
                            ("map_categories", "Map Inconsistent Categories"),
                            ("filter_rows", "Filter Records by Condition"),
                            ("handle_outliers", "Handle Outliers"),
                        ],
                        max_length=50,
                    ),
                ),
                ("column_name", models.CharField(blank=True, max_length=255)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("affected_rows", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="CleaningRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("target_schema", models.JSONField(blank=True, default=dict)),
                ("steps_config", models.JSONField(blank=True, default=list)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_recipes",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TransformationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_type", models.CharField(default="manual", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("steps_count", models.PositiveIntegerField(default=0)),
                ("rows_before", models.PositiveIntegerField(default=0)),
                ("rows_after", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
