# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cleaning", "0001_initial"),
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationrun",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transformation_runs",
                to="datasets.dataset",
            ),
        ),
        migrations.AddField(
            model_name="transformationrun",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs_from_version",
                to="datasets.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="transformationrun",
            name="target_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs_to_version",
                to="datasets.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="transformationstep",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="cleaning.transformationrun",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cleaningrecipe",
            unique_together={("workspace", "name")},
        ),
    ]
