# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        ("semantic_model", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales_mis", "Sales Performance MIS"),
                            ("finance_mis", "Financial & Revenue MIS"),
                            ("inventory_mis", "Inventory & Stock MIS"),
                            ("operations_mis", "Operations & Workflow MIS"),
                            ("hr_mis", "Human Resources & Attendance MIS"),
                            ("custom_mis", "Custom Governed MIS Report"),
                        ],
                        default="custom_mis",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date_column", models.CharField(blank=True, max_length=255)),
                ("metric_columns", models.JSONField(blank=True, default=list)),
                ("dimension_columns", models.JSONField(blank=True, default=list)),
                ("filters_config", models.JSONField(blank=True, default=dict)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_definitions",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "semantic_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="semantic_model.semanticmodel",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_definitions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameters_applied", models.JSONField(blank=True, default=dict)),
                ("summary_kpis", models.JSONField(blank=True, default=dict)),
                ("table_data", models.JSONField(blank=True, default=dict)),
                ("chart_payloads", models.JSONField(blank=True, default=dict)),
                ("excel_export_path", models.CharField(blank=True, max_length=512)),
                ("pdf_export_path", models.CharField(blank=True, max_length=512)),
                ("csv_export_path", models.CharField(blank=True, max_length=512)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="datasets.datasetversion",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="reports.reportdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
