# Generated by Django 6.1.1 on 2026-10-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=255)),
                ("observed_value", models.FloatField()),
                ("baseline_value", models.FloatField()),
                ("deviation_percent", models.FloatField(default=0.0)),
                ("z_score", models.FloatField(default=0.0)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical Outlier / Extreme Spike"),
                            ("warning", "Warning / Noticeable Deviation"),
                            ("info", "Informational / Low Variance"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(default="statistical_zscore", max_length=64),
                ),
                ("evidence", models.TextField()),
                ("period_label", models.CharField(blank=True, max_length=128)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("open", "Open / Needs Attention"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=255)),
                ("date_column", models.CharField(max_length=255)),
                ("method", models.CharField(default="linear_trend", max_length=64)),
                ("historical_points", models.PositiveIntegerField(default=0)),
                ("horizon_periods", models.PositiveIntegerField(default=3)),
                ("forecast_results", models.JSONField(default=list)),
                ("mae_error", models.FloatField(blank=True, null=True)),
                ("assumptions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
