# Generated by Django 6.1.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(blank=True, max_length=255)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("missing_values", "Missing Values"),
                            ("duplicate_rows", "Duplicate Rows"),
                            ("invalid_date", "Invalid / Unparseable Dates"),
                            ("invalid_numeric", "Invalid Numeric Format"),
                            ("outlier", "Statistical Outlier (3+ Std Dev / IQR)"),
                            (
                                "inconsistent_casing",
                                "Inconsistent Text Whitespace / Casing",
                            ),
                            ("category_variation", "Fuzzy Category Variations"),
                            ("broken_rule", "Broken Business Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Informational"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("affected_row_count", models.PositiveIntegerField(default=0)),
                ("evidence_summary", models.TextField()),
                ("sample_row_indices", models.JSONField(blank=True, default=list)),
                ("suggested_action", models.CharField(blank=True, max_length=64)),
                ("suggested_params", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_issues",
                        to="datasets.datasetversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-affected_row_count"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.FloatField(default=100.0)),
                ("completeness_score", models.FloatField(default=100.0)),
                ("uniqueness_score", models.FloatField(default=100.0)),
                ("validity_score", models.FloatField(default=100.0)),
                ("consistency_score", models.FloatField(default=100.0)),
                (
                    "scoring_formula",
                    models.TextField(
                        default="Score = 100 - (missing_pen + dup_pen + invalid_pen + outlier_pen)"
                    ),
                ),
                ("total_issues_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_report",
                        to="datasets.datasetversion",
                    ),
                ),
            ],
        ),
    ]
